### ISSUE TITLE
[Suggestion] Player select screen

### ISSUE THREAD

**Issue by ruvaldak** [MrNavaStar/InvSync#10]
While the current intent is for this to be used on Fabric servers, as an SSP mod, this allows the game to have functions similar to Terraria. However, unlike Terraria, you can only have one instance of your player. Would be neat to be able to create multiple invsync instances, all with different inventories, which you can change between either by a mod menu config, or upon loading a world.

**Comment by MrNavaStar** [comment]
This is an interesting idea. The primary use of the mod is for more for server side use cases, but I would be willing to add better client side support. I do however have some much more pressing projects, so I probably wont get around to this for a few more months at the soonest

**Comment by MrNavaStar** [comment]
As this is outside the scope of this mod, this issue is being closed
