### ISSUE TITLE
help

### ISSUE THREAD

**Issue by ghost** [MrNavaStar/InvSync#14]
hey, this isnt an issue its more so support but whenever i start the server i get a permission denied and it crashes. i set the sqlite path to /var/www/mounts and im pretty sure thats a root path so im wondering if theres any paths i can set it to that wont get me permission denied. so sorry i have to ask this way i just cant find help anywhere else

**Comment by MrNavaStar** [comment]
You could mount it under your home directory, or you can just run chmod +x on what ever directory you decide to put it at
