### ISSUE TITLE
Tables not creating with MYSQL?

### ISSUE THREAD

**Issue by PandaGGuy** [MrNavaStar/InvSync#16]
Trying to get the latest build working on my 1.18.1 Fabric server. 

I haven't been able to get the SQL script to create the tables. Do you have a list of tables needed in MYSQL to work? Or a possible workaround? Ik there is SQLITE but I can't even get the server to start when set to SQLite.
[latest (1).log](https://github.com/MrNavaStar/InvSync/files/7698585/latest.1.log)

**Comment by MrNavaStar** [comment]
Odd. I can't actually view that log link. I'll take a look if you can fix that.

**Comment by PandaGGuy** [comment]
Weird. I just uploaded the log to github O.O
Here is it on an external site: https://mclo.gs/5qzTWL8

**Comment by MrNavaStar** [comment]
Are you trying SQLite or mysql? I believe mysql is kinda broken, SQLite has been working for others and myself. 

If your having issues on SQLite, make sure the server has permission to edit the directory your asking it to to put the database at. You can do a simple chmod on Linux, idk on windows.

**Comment by PandaGGuy** [comment]
I was using MYSQL.

I have tried SQLITE but i have been running into permission issues. I think it has someting to do with my pterodactyl setup. I do have a mounted directory and pterodactyl does have permission to read/write/execute from the shared directory but I keep getting a "Failed to connect to database! Is there already a connection open."  Are you active in a particular discord? I can move convo/support to there since this may just be an issue related to my setup

**Comment by PandaGGuy** [comment]
Cloned the db to a new directory and redid permissions did the trick. Closing this!
