### ISSUE TITLE
When the server restarts, the players' NBT is cleared.

### ISSUE THREAD

**Issue by Khikki** [MrNavaStar/InvSync#17]
I noticed another serious error, when restarting the server, things from the players' inventories disappear.

**Comment by MrNavaStar** [comment]
Is this a graceful shutdown? Or are you throwing a SIGINT or SIGKILL.

**Comment by Khikki** [comment]
I just stop one of the servers, /stop. 
I will make a video if I cannot repeat it, I will use the latest build on GitHub.

**Comment by Khikki** [comment]
I apologize for the panic, I found out why this was happening, it was because of a conflict with the GolfIV mod, https://modrinth.com/mod/golfiv
I think it should be indicated so that others do not encounter this. :0

**Comment by MrNavaStar** [comment]
Sounds good
