### ISSUE TITLE
What is the correct format for the Database_Directory setting for linux?

### ISSUE THREAD

**Issue by dandin87** [MrNavaStar/InvSync#2]
I attempted numerous ways and it kept crashing on startup from this line not being correct. I was testing on Bisect Hosting. Since your example is clearly windows I was not sure if another way is implemented. Most people are going to be running on Linux though, so you might want to include an example for that. 

This is what I have for windows which works fine, however, I would not know the linux drive on a host. 
"Database_Directory": "C:/Users/Trent87/Downloads/AoF3_2.7.0_dev.alloffabric.com"

Here are some of the things I tried.
"Database_Directory": "root"
"Database_Directory": "/"
"Database_Directory": "root/"
"Database_Directory": "\"
"Database_Directory": "root\"

**Comment by MrNavaStar** [comment]
On my Linux server I store all my servers under /var/lib/servers. Idk how much access Bisect Hosting give u on your vps,

**Comment by MrNavaStar** [comment]
Odd, it works fine on my Linux server (using dir /var/lib/server). The home dir SHOULD be "/", my best guess is that bisect hosting doesn't give you permission to edit the home dir (could be wrong Ive never used it). Ill look into it here.

**Comment by MrNavaStar** [comment]
Okay yeah, its definitely a permission issue. "/" works as long as the server has permission to use it. For me a simple chmod +x / solves the problem. Ill update the config in the next release to be Linux format instead

**Comment by dandin87** [comment]
Ah, ok good. Our NA server is dedicated so we won't have permission issues there. Just wanted to confirm those settings should have worked. I will mess around with the settings on Bisect to see if I can get it to work. It will be interesting if we can get Velocity and this working together to be able to have multiple servers running separate dimensions or whatever and keep inv synced. And maybe have a lobby server. We have a pretty consistent 15-25 players on our NA server and 10-20 players on EU. 25 is pretty much the max we can currently handle and keep 20 tps in urvival without offloading the dimensions. Not sure how many modded survival servers can do that without being paper/bukkit/sponge servers.

**Comment by MrNavaStar** [comment]
I run this on my servers with velocity and it works great. Just make sure WAL mode is false when using a proxy as it fails to sync correctly with it on because the switch from server to server is instant.
