### ISSUE TITLE
How to configure profiles?

### ISSUE THREAD

**Issue by KEVIN910919** [MrNavaStar/InvSync#20]
How to configure profiles?
I use mysql
Sorry my English is not good (Google Translate)

**Comment by MrNavaStar** [comment]
Not sure what you mean by profiles

**Comment by KEVIN910919** [comment]
![unknown](https://user-images.githubusercontent.com/84594248/162972498-86809d96-d3fc-4c64-b5ce-9af41249523f.png)

**Comment by MrNavaStar** [comment]
Yeah sorry still don't know what you issue is

**Comment by MrNavaStar** [comment]
I am closing this as I have gotten no response in 2 months
