### ISSUE TITLE
Lost data on any event other than proper disconnect. Synchronize all every now and then.

### ISSUE THREAD

**Issue by Bizzonium** [MrNavaStar/InvSync#24]
As i see in code synchronization happens only on player disconnect. If server crashed or stopped data could be lost.

**Comment by MrNavaStar** [comment]
This might be a good idea

**Comment by Bizzonium** [comment]
https://github.com/MrNavaStar/InvSync/pull/26

**Comment by MrNavaStar** [comment]
Fixed by #35
