### ISSUE TITLE
Lags on players join

### ISSUE THREAD

**Issue by Morb0** [MrNavaStar/InvSync#25]
It seems that because of this decision with `sleep` on every connection server just freeze for 1 second and have TPS drops.
https://github.com/MrNavaStar/InvSync/blob/95d04de8c7aa9f315b2e3e6b91a790c26b9e90eb/src/main/java/mrnavastar/invsync/InvSync.java#L46
What is the purpose of this?

**Comment by MrNavaStar** [comment]
Word sleep probably isn't great cause the whole thread sleeps. But I have never actually seen this cause any lag in my testing. We need this delay to stop the wrong server from taking control of the database

**Comment by MrNavaStar** [comment]
Man, only took me 6 months haha. This issue should be resolved in the latest release. Let me know if you still run into issues
