### ISSUE TITLE
[Ask] InvSync on single player world

### ISSUE THREAD

**Issue by snackmasta** [MrNavaStar/InvSync#37]
Is this mod working in a single-player world, what I mean is syncing inventory between two or more different worlds from separate devices. For example, two worlds in two separate devices with two different users and MC accounts frequently join each other world via LAN or "LAN" with third-party mod while bringing their own inventory/playerdata. Is it works like that?

**Comment by MrNavaStar** [comment]
I guess you could get it to work if you pointed both clients mod configs to the same mysql server. Its not really intended for that but I dont see why it wouldn't work
