### ISSUE TITLE
Isn’t real time sync

### ISSUE THREAD

**Issue by Howie0715** [MrNavaStar/InvSync#6]
When I join the B server,the player data in A server didn't save yet,so I will read the old player data in B server

**Comment by MrNavaStar** [comment]
This has been fixed in the latest 1.17 release

**Comment by Howie0715** [comment]
I use the latest release,but it's the same situation. I join in the B server and read the player data at [00:00],but the player data in A server save at [00:07]....so I will read the old player data in B server.

**Comment by MrNavaStar** [comment]
How are you joining server B before leaving server A? I can confirm that real time syncing works no problem, so it sounds like a setup issue.

**Comment by MrNavaStar** [comment]
If your a putting this on a server with existing data, the server you join first will be the one that gets synced across both.

**Comment by Howie0715** [comment]
> How are you joining server B before leaving server A? I can confirm that real time syncing works no problem, so it sounds like a setup issue.

I use velocity as proxy,so just "/server B" to join server B

**Comment by Howie0715** [comment]
> If your a putting this on a server with existing data, the server you join first will be the one that gets synced across both.

Yes ,so I set Serve A the main server

**Comment by MrNavaStar** [comment]
Okay I too test with a velocity proxy, and it works fine for me. If your main server is server A, and you also join it first, there should be no issue. 

Double check that your directory and database name matches in both configs (database names should end with .db), as well as that it is a valid location. For linux it should be /my/dir, and for windows it will be C:/my/dir.

If it is a linux server, be sure the minecraft server has permission to edit the files. chmod +x will fix it in most cases. (or chmod 777 but you should know what your doing)

**Comment by MrNavaStar** [comment]
There is not much I can do for you beyond that as the latest release works perfectly on my velocity server. Transferring using /server <name> gives me no problems

**Comment by Howie0715** [comment]
My hypothetical situation is I have {apple} in A server, and I go to the B server, the {apple} exist , but I get another item {carrot} in B server , go back to A server ,the item that I get in B server didn't appear

**Comment by Howie0715** [comment]
So I edit the code to delay 10s to read the playerdata when I corss the server in order to wait the inv sync save the data properly.
This method work ,but I need to wait for 10s

**Comment by MrNavaStar** [comment]
hmmmm, that is very odd. Is possible I uploaded a bad jar. try downloading it from a different source, its available here, on modrinth and curseforge.

**Comment by MrNavaStar** [comment]
Building from source may also fix the issue for you (so just remove your 10 second thing). If the problem persists unfortunately I wont be able to assist until next weekend. Thanks for your patience.

**Comment by Howie0715** [comment]
Thank for your assist :D
