### ISSUE TITLE
Latest version file - 2.0 - is named 1.0 on curseforge.

### ISSUE THREAD

**Issue by K0-RR** [MrNavaStar/InvSync#8]
Not a bug but still can be an issue. Also This mod size of huge, I know it's because sql library but maybe you can cut unused parts of it?

**Comment by MrNavaStar** [comment]
Oh Ill fix that on curse. Thanks! Unfortunately all the size comes from the sql drivers. InvSync is only 160 ish lines of code, and even sqlib is only 300. the 12mb comes from the mysql and sqlite driver.
